### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by adam9899** [someaddons/dungeonbosses#1]
**Describe the bug**
Crash on launch

** Mod version **
brutalbosses-2.2.jar

** Logs **
Latest/Crash log
[latest.log](https://github.com/someaddons/dungeonbosses/files/7921339/latest.log)

**Comment by adam9899** [comment]
Issue with big brain perhaps?

**Comment by someaddons** [comment]
ye mixin conflict with bigbrains

**Comment by someaddons** [comment]
fixed in v2.3
