### ISSUE TITLE
[Bug]: Boss bar continually disappears when shooting bosses at a distance

### ISSUE THREAD

**Issue by JetpackRescue** [someaddons/dungeonbosses#10]
### Describe the bug you're experiencing

When you get any decent distance away from the boss, the boss bar disappears, then when you injure the boss, it shows back up. Could you please add a config setting to always show the boss bar if you're within a configurable distance. I have boss music that plays when a boss bar shows up and it's turning the music on and off. I don't think you should have to shoot the boss to see the boss bar, a configurable relative distance from the boss should trigger the boss bar. With my situation I have crayfishs gun mod, so if I shoot the boss from too far away the boss bar shows then hides immediately. If I'm closer and shoot the boss it will show the boss bar but if I back up(because I've made the bosses hard enough to match the effectiveness of the guns) then it disappears. Every time the boss bar shows up it triggers the boss music, if It disappears it stops it, so it's kind of chaotic.

Another issue I've encountered is if I take a boss from another mod and want to use him with brutal bosses, it now shows 2 boss bars - the brutal boss bar and the bosses original boss bar. Maybe a config option to hide the boss bar in each bosses data pack config file would help with these situations.

### Reproducability

Explained above

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

None

**Comment by someaddons** [comment]
fixed in 3.1
