### ISSUE TITLE
[Bug]: Custom attribute "dropgear" doesn't work

### ISSUE THREAD

**Issue by addaonez** [someaddons/dungeonbosses#11]
### Describe the bug you're experiencing

Whether I use this attribute or not, all the same, all items drop from bosses. In NBT tags, all the chances of items dropping are 0.085f, although I need to accurately drop the chestpiece and definitely not drop the rest of the items

### Reproducability

Try to summon any boss and kill him, this attribute does not work for anyone

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/addaonez/fcb6d893a0ce777bf9f999470623d9e9

**Comment by someaddons** [comment]
Dropgear currently does not allow you to drop only one specific item:
```
dropgear Specifies which gearslots the boss drops on death, values 1-6, 6 drops all slots. Slot order: 1. mainhand 2. offhand 3. feet 4. legs 5. chest 6. head
```

If you specify 5 for the chest, then it'll drop all slots up to the chest slot

**Comment by addaonez** [comment]
Thanks for the answer.
Is it possible to somehow change NBT tags for bosses in advance? ArmorDropChances and HandDropChances.

**Comment by someaddons** [comment]
not yet, but planning to add nbt support to the boss entity itself

**Comment by addaonez** [comment]
it would be great!

**Comment by someaddons** [comment]
added nbt support
