### ISSUE TITLE
Hide boss nametag

### ISSUE THREAD

**Issue by JetpackRescue** [someaddons/dungeonbosses#12]
I've changed the boss' name into an image to make the boss bar look better. The issue I'm having is that the image for the boss bar also shows above the boss' head. Could you add an option to hide the boss' nametag?

I'm using a method where I reference a language file in my resource packs textures/font location, this replaces the name of the mob with an image. It looks like this in the boss' config file:

```
{
  "entity": "goblinsanddungeons:hobgob",
  "name": "\uE200",
  "visualscale": 1.2,
  "effects": {
    "minecraft:resistance": 1,
  }
```
I haven't found any other way to add an image to the boss bar.

Two other thoughts, what would be really neat is if we could hide the nametag above the mob, and add a specific image in the config that would show above them, like an X or a skull or a triangle to signify that entity as the boss. Second thought is to be able to choose the color of the boss bar for the mob, since a purple boss bar would make sense for a purple boss.

thanks for the consideration.

The bossbar image i'm using is a test image to get it lined up, which is where I realized the issue I'm having.
![2022-03-28_01 31 23](https://user-images.githubusercontent.com/49115565/160358767-3787ed29-3c49-424d-8991-b741a47075a5.png)

**Comment by someaddons** [comment]
added
