### ISSUE TITLE
[Suggestion] Boss locked Chests module or addon.

### ISSUE THREAD

**Issue by Darkmega18** [someaddons/dungeonbosses#13]
So I noticed that your bosses spawn at the location of loot chests when they're spawned as part of dungeons.

In recent times myself and some others working on a modpack have desired a mod that basically allows us to lock certain chests and provide some kind of challenge before they can be accessed.

We have the mod "Locks" by Melonslise, however it's currently become a little buggy and lootr recently made some changes which has caused some other weirdness.

So we come to this suggestion:
I'd like to request the ability to produce a lock or shield of some kind of a chest which is compatible with lootr. When the shielded chest is interacted with the chest instead causes some particles to happen and then spawns a boss who is compatible with the chest to fight you.

As long as the shield detects the boss is in a wide area the boss doesn't despawn and the chest will not open.

Defeating the boss drops a key which doesn't fall like a normal item which can't be destroyed by environmental hazards (basically similar to how enigmatic legacy does it's inventory saving feature for it's enigmatic amulet, if you need a reference of how it should act).
The key can be collected and then used to break open the chest afterwards.

Among this idea, there could be other avenues to break open chests also after the initial "straight forward" way of spawning and beating a boss.
 Such as the aggressive option, where you can attack the chest instead with mining gear to break it repeatedly to weaken the shield and break into it this way. However it angers the boss giving them buffs or additional skills if they detect their chest being tampered with, while also immediately locking onto their chest's aggressor.
or the stealth option, where you can find or create special items based on the chest to unlock them with a time delay without aggravating the boss and sneak away with the gear.

Would this be a plausible addon or mechanic which could be created?

**Comment by someaddons** [comment]
keys is kind of difficult, but I could prevent the position to be interacted with/display a message to the player. Probably also should apply a glow effect to the boss so the player can find it

**Comment by someaddons** [comment]
added in v5.0

**Comment by Darkmega18** [comment]
Can I request this lock stuff be backported to 1.16.5 so I can actually use my own suggestion in the modpack I hoped to use it in? :<
