### ISSUE TITLE
[Suggestion] Champions, Apotheosis, special AI cross compatibility among others.

### ISSUE THREAD

**Issue by Darkmega18** [someaddons/dungeonbosses#14]
To allow maximum shenanigans cross compatibility could be considered with other mods which have the capacity to do things to mobs.

**Some initial suggestions if possible:** 
With **champions** _(by TheIllusiveC4)_ available, pack makers can make a boss spawn additionally as a specific champion tier with preset champion skills, or with a random assortment of champion skills based on tier. If compatibility is made for a default boss, but champions is not installed, the portion is simply ignored and the boss is made normally just without the intended champions bonuses.

With **Apotheosis** _(by Shadows_of_Fire)_ available, pack makers can instead pass the boss naming to the random name generator of apotheosis affix items to handle so that the boss has a different name each time.
Further, the boss's gear can be rolled with a chance to become affix gear of the desired weight level gaining affixed properties and having it's preset enchantments overriden or added to. The item being dropped on death.

With **special AI** _(by Fathertoast)_ available bosses can be pre-specified to spawn with AI skills from fathertoasts mod also. Such as leaping, grabbing/ally throwing, shaman powers, dispenser head, charge attack etc.

**Comment by someaddons** [comment]
I'm planning to add support for creating boss entities from their NBT data, which should take care of most of these suggestions, as you then can make e.g. a champion entity with two stars, save it as NBT via command and put it into the boss datapack file to load. Then it'll always be a boss with two stars.

**Comment by Darkmega18** [comment]
I guess that works too. Slightly tougher to throw together nbt for apotheosis bosses though.

What about the ability to list multiple items to a slot to give them a chance to have one of them? So that bosses can be slightly varied? Or is brutal bosses made to be used to create specific bosses rather than have them be generated?

**Comment by someaddons** [comment]
Ye it is more for designed bosses, which facilitate how the fight plays out^^ added nbt support
