### ISSUE TITLE
[Suggestion]: Making the brutal bosses exempt from activating pressure plates

### ISSUE THREAD

**Issue by BugmanBugman** [someaddons/dungeonbosses#15]
### Describe the bug you're experiencing

Making the brutal bosses exempt from activating pressure plates. This would be nice because sometimes a boss can spawn in the bottom of a vanilla desert pyramid and set off the pressure plate, destroying all the loot, and i think this is rather unfai
![2022-04-02_01 40 02](https://user-images.githubusercontent.com/40730042/161370864-a77f696d-60c0-4d5d-9a9e-eac87e87cec7.png)
r

### Reproducability

x

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

x

**Comment by someaddons** [comment]
fixed
