### ISSUE TITLE
[1.16.5] [Bug]: Crash brutalbosses:thrownitem

### ISSUE THREAD

**Issue by Cixon** [someaddons/dungeonbosses#16]
### Describe the bug you're experiencing

Entered a [IllagerPlus](https://www.curseforge.com/minecraft/mc-mods/illagers) structure with the intention of killing the enemies but was met with a crash due a Vindicator throwing a ender pearl.

### -Install 1.16 BrutalBosses-v3.2
Spawn a Vindicator that can throw ender-pearls.
Enter survival mode
See report.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/Cixon/ac4d7e866fc48acd550d220f6c37f0cf

**Comment by Cixon** [comment]
**note:** i did not modify any configuration options for dungeonbosses.

**Comment by someaddons** [comment]
Its actually the mod `betterinvisibility` causing the crash, not brutal bosses

**Comment by Cixon** [comment]
ok will report to that dev, thanks!
