### ISSUE TITLE
[Bug]: issues replacing/editing defaults

### ISSUE THREAD

**Issue by Darkmega18** [someaddons/dungeonbosses#17]
### Describe the bug you're experiencing

I have an issue where I'm trying to replace the archmage boss with a necromancer boss from eidolon. however when I replace the archmage file in my datapack it doesn't override it.
however I can rename the same file necroboss and spawn that with no issues at all.

### Reproducability

Pick a boss.
Replace the boss's file using an external datapack loaded through openloader with another custom boss.
also save a fresh copy of replacement boss under a different name.
optional: likely get hit with apotheosis errors, cause sharing the same space...
attempt to load the boss ingame from the overwritten boss file.

it'll probably spawn the original boss.
But provided your boss file works properly, loading the same boss from the uniquely named file that didn't exist in the original mod works.

I'm tempted to think the reason this fails is because of the known issue with apotheosis existing also. but I'm not sure otherwise.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/Darkmega18/60e9ca3872ffb344963f95bebf5ea77b

**Comment by someaddons** [comment]
works just fine for me with open loader, you probably want to upload your custom datapack there is likely some mistake in it.

**Comment by Darkmega18** [comment]
I literally just crossed out the list of spawn locations from the bottom of them so I could edit them down the line and re-allocate them places around the pack.

then with the archmage it's literally the exact file that I turned into a necromancer boss file separate from the archmage's file which I then spawned afterwards after a reload and fought (which prompted the other issue report). so it was definitely working. ._.

openloader and apotheosis causing bugs? not just openloader. it's in a modpack currently.

**Comment by someaddons** [comment]
apotheosis is just trying to read the file and notices its in the wrong format, prints an error and skips. Thats not an actual issue.
With openloader I made a quick datapack which changed the archmage entity to a zombie instead and it worked just fine, so I guess there is sth wrong with your datapack

**Comment by Darkmega18** [comment]
Alrighty. I'll extract them again from the jar and edit them slower this time, maybe in their own datapack and see if they work. but theres no errors coming up for brutal boss itself, and if I make something invalid you'd chuck an error right?
Leaving the loot tables spawn list empty can stop something from spawning can't it? I just want to dummy most of the existing ones out...

**Comment by Darkmega18** [comment]
well that worked. weird. guess I'll go bigger from here then. and see where it breaks.
