### ISSUE TITLE
[Bug]: The Llama spit shot by "spitcobweb" doesn't despawn in an open area.

### ISSUE THREAD

**Issue by RedPxnda** [someaddons/dungeonbosses#19]
### Describe the bug you're experiencing

A boss with the "spitcobweb" goal shoots llama spit as expected, but since this spit has no gravity, its not unlikely it gets stuck in the air and never despawns. 
Underground, this isn't an issue as in theory the spit should hit a block. But, on the surface, it is a very common occurrence. 

### Reproducability

Self explanatory.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

- n/a

**Comment by someaddons** [comment]
fixed in 3.4, was missing a max lifetime
