### ISSUE TITLE
[Bug]: Summoned mobs always gain an iron sword. Can't change it. please stop.

### ISSUE THREAD

**Issue by Darkmega18** [someaddons/dungeonbosses#20]
### Describe the bug you're experiencing

![image](https://user-images.githubusercontent.com/8104689/163706521-f9938e42-4d99-4652-9814-ee83191594eb.png)
My summoned mini-bosses and other helpers etc of a particular boss I'm trying to perfect is having issues. The katana is meant to spawn in their main hand, but it's being immediately overridden by an iron sword. 
I have a feeling this is your doing. the same nbt I give it spawns the katana just fine when spawned as a boss directly _(the nbt contains brutal boss nbt to give the summon skills and special ai ai also)_, and also when spawned through a command.

This also likely explains why I get completely obliterated by these chickens in one of my other bosses, because suddenly they all have the stagger and damage power of a free iron sword I can't see:
https://streamable.com/cg13gj

### Reproducability

yes.
it just happens.

make a boss, make it summon nbt'd or otherwise mobs.
summoned mob gets a free sword. Before I was canceling the loot table with an empty table so the summons are less farmable I was SO confused why my inventory was full of mostly broken iron swords mixed in with the chicken feathers and meat of the cucko boss's minions.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

nothing to log. it's not an error of the datapack but the mod when it spawns these things in.

**Comment by someaddons** [comment]
fixed in 3.3, was a leftover from before summoned mobs could be customized via nbt

**Comment by Darkmega18** [comment]
alrighty. thank you.
