### ISSUE TITLE
[Bug]: After updating after last issue, now my summoned minions can't inherit brutal ai effects through nbt.

### ISSUE THREAD

**Issue by Darkmega18** [someaddons/dungeonbosses#21]
### Describe the bug you're experiencing

Two versions ago, on version 3.2 that I had when I made this issue: https://github.com/someaddons/dungeonbosses/issues/20
I had the capability to summon mobs with other brutal boss ai capabilities by putting it into their nbt. I did that during the chucko fight that I sent a streamable of to make all the chickens fight.

But today, after checking to see that the fix was actually fixed now in version 3.4 I'm noticing that my royal blademaster aspects as in the picture from the other issue no longer have their abilities. Such as spawning with resistance etc, or using their potion ai also or using their projectiles and charges.
The chickens are also completely returned to chickens and don't get the name from the boss or the ai or anything and instead just scatter and run around now...

I think this is a step back.

### Reproducability

take the forgecap out of the boss nbt get read out and use it to spawn a mob with boss ai using 3.2. _(change the samuraidark to some other boss)_

ForgeCaps:{\"brutalbosses:bosscap\":{bbosspath:\"samuraidark\",bbossnamesp:\"brutalbosses\"}}

then try it in 3.4, no effect now for some reason. 
mob spawns with gear in the rest of the nbt etc, but doesn't inherit the ai stuff, which rendered making a funny boss like [this](https://streamable.com/cg13gj) null in the latest version.
The chickens were attacking like this until I updated and now they're reverted to basic chickens with no attacks cause the ai isn't taking effect.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

nothing to log, it doesn't produce an error unless somethings wrong with the json. but theres nothing wrong, cause I can spawn the boss still. just the functionality dropped off.

~~also, nbt for bosses themselves please. I really want it...~~

**Comment by someaddons** [comment]
ye that is not intended, should be loading nbt summons just fine

**Comment by Darkmega18** [comment]
Will be fixed?

**Comment by someaddons** [comment]
fixed

**Comment by Darkmega18** [comment]
eeeexcellent x2.
