### ISSUE TITLE
[Bug]: "ownerdamagepct" is damaging the boss when summonedmobs are summoned, not die

### ISSUE THREAD

**Issue by Jetpack-Cat** [someaddons/dungeonbosses#22]
### Describe the bug you're experiencing

have a boss with `brutalbosses:summonmobs`, add `"ownerdamagepct": 30`, the first time any mob is summoned from the boss there's no damage, killing the summoned mobs doesn't do damage, but the second time the mobs are summoned watch a huge chunk of the bosses health go down.

### Reproducability

read above

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs and Datapacks

none

**Comment by someaddons** [comment]
fixed
