### ISSUE TITLE
[Bug]: Wither Skeleton in bastion?

### ISSUE THREAD

**Issue by Niketats** [someaddons/dungeonbosses#24]
### Describe the bug you're experiencing

Wither skeleton boss spawns on bastion, it's strangw because piglims hates wither skeletons
![2022-05-02_22 24 08](https://user-images.githubusercontent.com/68917520/166312306-52188f52-ee65-456b-82f6-209a549cc42c.png)

### Reproducability

find bastion

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs and Datapacks

there is nothing interesting in logs

**Comment by someaddons** [comment]
fixed in 4.8

**Comment by Niketats** [comment]
oh, but i'm using 1.16.5 :D
