### ISSUE TITLE
[Bug]: Brutal Bosses seems to have crash my game

### ISSUE THREAD

**Issue by justawander** [someaddons/dungeonbosses#27]
### Describe the bug you're experiencing

when i was loading minecraft and went to my mod loader page the game crashed for me with Brutal Bosses being one of the mods said to be responcable

### Reproducability

my fire guess is to download starlight with Brutal Bosses installed and then go to the mod loader page

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs and Datapacks

https://bytebin.lucko.me/C2vIzhp4hW

**Comment by someaddons** [comment]
seems alex's mobs is creating an entity without a level, adding a workaround but shouldnt really happen in the first place.
