### ISSUE TITLE
[Bug]: Owner Damage Percent first kill 1.18.2

### ISSUE THREAD

**Issue by Tyrius1** [someaddons/dungeonbosses#28]
### Describe the bug you're experiencing

Trying to bring back the Grave Digger boss I made in 1.16!
"ownerdamagepct": 0f, using this on one of my wip bosses and regardless what I set the amount to it almost entirely kills the boss from the first minion slain. The rest of the minions slain do what looks like close to the actual percentage set.

### Reproducability

To reproduce create evoker boss with summon zombies and set owner damage to any number. Tested 5, 1, 0.05 and 0.01
All will produce the same amount of damage done to the boss when the first of the minions are slain.
Other minions summoned in the same wave will do much less damage to the boss. 
I shared the Grave Digger setup below.

Using 1.18.2 but selection box below doesn't have that option. 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/Tyrius1/f22498cea9b1c19ebdd800b26aa166d6

**Comment by someaddons** [comment]
fixed in v5.0
