### ISSUE TITLE
[Bug]: duplicate spawns in one spot

### ISSUE THREAD

**Issue by MacChuck** [someaddons/dungeonbosses#30]
### Describe the bug you're experiencing

Not sure if this is a bug or a feature request, or a balance adjustment. Treasure chests in shipwrecks and underwater tend to spawn multiple copies of the drowned boss. I've seen 3 of the same boss along with a few normal drowned mobs. Is there a way to have them not spawn in duplicate and triplicate around the same treasure?

### Reproducability

Visit underwater shipwrecks

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs and Datapacks

n/a

**Comment by someaddons** [comment]
Adding functionality reducing similar spawns too close to eachother, with configurable distance. Fixed in 5.0
