### ISSUE TITLE
[Bug]: Bosses have permanent Glow

### ISSUE THREAD

**Issue by Nyaromight** [someaddons/dungeonbosses#31]
### Describe the bug you're experiencing

The bosses, which naturally spawns, have a permanent Glow effect. I see them through everything. When I use the command to spawn a boss, they dont have it.

### Reproducability

Finding another one or creating a new world.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/Nyaromight/20d7bd5ce339602e26a16da752d2f79c

**Comment by someaddons** [comment]
that is normal, some of the bosses have a glow potion effect. Simply the way those bosses are meant to be^^
Usually indicates either an interesting place to find, or that the boss has high difficulty
