### ISSUE TITLE
[Minor Bug]: Mixin failure on BasePressurePlateBlockMixin, the specified mixin class was not found

### ISSUE THREAD

**Issue by NighthowlerStudios** [someaddons/dungeonbosses#32]
### Describe the bug you're experiencing

During startup the log spits out information about a mixin failure.  No behavioural difference was noticed, the game does not crash.

### Reproducability

Can occur by simply launching the mod on its own

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs and Datapacks

https://pastebin.com/Q1fM1y2P

**Comment by someaddons** [comment]
ye don't worry about this one, just a warning about a no longer existing file I forgot to remove. Probably won't bother updating the old version for this though, as its just a log thing
