### ISSUE TITLE
Graphical glitch when mod is installed[Bug]: 

### ISSUE THREAD

**Issue by Slimdude** [someaddons/dungeonbosses#33]
### Describe the bug you're experiencing

When looking in the direction of a boss, some tile entities and other mobs surrounding the boss are rendered black. They can also be seen through solid blocks giving the appearance of xray vision. Looking away from the boss makes the problem go away, and removing the mod from the game solves this problem completely.  

Here are some screenshots:

]https://imgur.com/o5713cU
]https://imgur.com/26UiLZr
]https://imgur.com/r9enGrR
(url)
Minecraft version is 1.18.2
The latest version of BrutalBosses is 1.18.2-4.9

I can post my modlist if you need it. 

### Reproducability

Install the mod, look in the direction of a boss (on the surface or underground makes no difference), and this problem occurs.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs and Datapacks

There is no log file associated with this issue

**Comment by someaddons** [comment]
Bosses do not have any rendering component to them, its simply a vanilla entity which gets a nametag and special abilities. If rendering is broken when looking at one you probably have a mod which has general rendering issues of name tags or boss bars
