### ISSUE TITLE
[Bug]: Whirlwind Crash

### ISSUE THREAD

**Issue by Tyrius1** [someaddons/dungeonbosses#34]
### Describe the bug you're experiencing

Server crash

### Reproducability

Unsure.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs and Datapacks

https://pastebin.com/kxxV5q1E

**Comment by someaddons** [comment]
fixed in 5.1^^
