### ISSUE TITLE
Crash on opening protected chest when in creative

### ISSUE THREAD

**Issue by kackalack** [someaddons/dungeonbosses#36]
When opening a chest that is protected while in creative on a multiplayer server the game will crash.

**Comment by Akaixz** [comment]
I've ran into the same issue, playing on 1.18.2 version, it crashed whilst trying to open a chest guarded by a wither skeleton boss on the nether fortress.

Crash log: https://gist.github.com/Akaixz/086efacb134d3e19215cdd5a4aeaf28c

**Comment by someaddons** [comment]
fixed, thanks for providing a crashlog unlike op
