### ISSUE TITLE
[Bug]: Hitbox does not scale with visualsize

### ISSUE THREAD

**Issue by Deathawaits4** [someaddons/dungeonbosses#37]
### Describe the bug you're experiencing

When increasing visual size higher than the base, the hitbox does not scale. This is very frustrating when fighting large bosses. 
This issue is very present for a few bosses, but especially the large pig which is nearly impossible to hit. 
There is a library called pehkui which has perfect scaling abilities for mods, if you dont want to implement your own, this may be a good choice to use for this issue.

### Reproducability

create a custom boss at around 2x scale and you wont be able to even remotely strike the mob on its model. 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs and Datapacks

no point as it is no real error.

**Comment by someaddons** [comment]
that is actually normal and intended, as entities would have a lot of trouble moving around when their actual hitbox would get bigger. I may try to make them more hittable on clientside isntead
