### ISSUE TITLE
[Bug]: Hitting a non-boss entity crashes the game

### ISSUE THREAD

**Issue by xarvex** [someaddons/dungeonbosses#38]
### Describe the bug you're experiencing

Simply hitting a mob that is not modified by the mod to be a boss crashes the game immediately, it appears to be a part of the code that assumes an entity is part of BossType.

Version is not actually 1.18.1, I am on 1.19.1 but there was no option labelled for it.
This is on Brutal Bosses 5.4.

### Reproducability

From my small testing, hitting any mob, whether hostile or not will crash the client.
The example logs provided details in the nether dimension, but it also happens in the overworld.

Mobs tested:
- Chicken
- Cow
- Fox
- Pig
- Zombie
- Zombified Piglin

The game appears to operate as intended when a boss mob is hit.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/Xarvex/fb30046dabc61a9b869bafb409e5208c

**Comment by someaddons** [comment]
fixed
