### ISSUE TITLE
[Bug]: Crashes the game when with Create mod

### ISSUE THREAD

**Issue by serialtasted** [someaddons/dungeonbosses#39]
### Describe the bug you're experiencing

After updating the mod it started to crash on startup. The log is attached

### Reproducability

On the latest version (1.18.2 - 5.3) the game crashes when paired with Create.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs and Datapacks

https://pastebin.com/WndfbJnV

**Comment by someaddons** [comment]
fixed
