### ISSUE TITLE
[Bug]: Crash on startup 1.18.1

### ISSUE THREAD

**Issue by LaBestiaBrutal** [someaddons/dungeonbosses#4]
### Describe the bug you're experiencing

Crashes the client and server on startup

### Reproducability

Using forge 39.0.85 and brutalbosses-1.18.1-3.7.jar

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/LaBestiaBrutal/38bd41aca50fcc73e6fd1e8fe829049e
https://gist.github.com/LaBestiaBrutal/1b0926679fefa8d041b11088501300d7

**Comment by someaddons** [comment]
fixed in 3.8!
