### ISSUE TITLE
Suggestion: Disable block destruction of Witch boss / Wandering Trader boss's magic attack

### ISSUE THREAD

**Issue by RedBeast1959** [someaddons/dungeonbosses#45]
brutalbosses-1.19.1-5.5.jar
Forge 43.1.32

Honestly, I like witch boss and wandering trader boss's magic attack, especially lightning summon projectile. But their destrutive power of magic attack which destroy blocks often cause lots of problems. Sometimes, they noticed me from far away and their magic projectile destroyed whole dungeon even before I reached that place. It was horrible experience when boss destroyed entire end city ship and blow up precious elytra. Also, occasionally, their attack destroyed the loot chest which they guarded.

**Comment by someaddons** [comment]
that can be adjusted via datapack already, the wither skull shoot AI has a `dangerous` flag which you can disable
