### ISSUE TITLE
[Bug]: Mod conflict with ArnicaLib

### ISSUE THREAD

**Issue by Saereth** [someaddons/dungeonbosses#47]
### Describe the bug you're experiencing

There is a conflicting Mixin with Arnicalib which causes the pack (FTB Inferno) to crash when both mods are present

### Reproducability

Minecraft 1.18.2
Forge 40.1.80

Minimum mods to reproduce:
brutalbosses-1.18.2-5.4
Arnicalib 5.6.1 

I have opened an issue with Arnicalib as well and they seem to have identified the issue but think it may be better resolved on your end if possible, link to the original issue here:

https://github.com/auioc/arnicalib-mcmod/issues/10

Thank you both for looking into it

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/Saereth/ffc47ae03a7c47b50b5586b3baf2f416

**Comment by someaddons** [comment]
fixed in 5.6
