### ISSUE TITLE
[Bug]: Mobs Animations Plus Conflict

### ISSUE THREAD

**Issue by Tyrius1** [someaddons/dungeonbosses#48]
### Describe the bug you're experiencing

I was in creative and right clicked a chest that was assigned to a brutal boss and I crashed as the Boss targeted me.

### Reproducability

I'm guessing to just add Mobs Animations Plus(mod id in crash report is vanilla_animations) alongside Brutal Bosses and wait for the AI/Animations to conflict. Will do further testing with just the two mods if crash report isn't enough info.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs and Datapacks

https://pastebin.com/FNHJXWBk

**Comment by someaddons** [comment]
looks like just the animations mod is crashing, bosses doesnt seem involved in this
