### ISSUE TITLE
[Bug]: Incompatibility with Corpse mod

### ISSUE THREAD

**Issue by K4N0** [someaddons/dungeonbosses#49]
### Describe the bug you're experiencing

While fighting and dying multiple times to Corbin The Rotten, I noticed that my corpse body was missing and all my items were lost.

### Reproducability

Have Corpse mod with no changes to the config made.
Have Brutal Bosses Mod installed.
Fight Corbin the rotten and die.
Corpse body gets destroyed and all items within it.
brutalbosses-1.18.2-5.6.jar
corpse-1.18.2-1.0.1.jar
Modpack: Cataclysm Zombie Apocalypse
https://www.curseforge.com/minecraft/modpacks/cataclysm-zombie-apocalypse

Latest Log:
https://pastebin.com/8XKMvdgM

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs and Datapacks

no data pack, latest log link in the description

**Comment by someaddons** [comment]
should be fixed in 1.19
