### ISSUE TITLE
[Bug]: Crashes on World load

### ISSUE THREAD

**Issue by Gaxon1** [someaddons/dungeonbosses#5]
### Describe the bug you're experiencing

Load a previous world, and world crashes at 100%

### Reproducability

Removing dungeonbosses allows the world to successfully load. Adding it back in and the crash continues as soon as the load reaches 100%

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/Gaxon1/0b6d82e28a831455421d407980921e7a

**Comment by Gaxon1** [comment]
Seems to be a conflict with Infernal Mobs

**Comment by someaddons** [comment]
fixed
