### ISSUE TITLE
[Bug]: When killing a boss with special abilities, fireballs don't disappear for a long time

### ISSUE THREAD

**Issue by RandomGuy91** [someaddons/dungeonbosses#51]
### Describe the bug you're experiencing

When killing a boss with special abilities, fireballs don't disappear for a long time. I don't know if this happens for every boss, or just the wandering trader.

### Reproducability

IDK, but I'm playing with a lot of mods so that might be an issue if it works for you.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs and Datapacks

N/A

**Comment by someaddons** [comment]
ye this is kinda normal, those projectiles have a longer timeout and are normally controlled by the entity, if it dies they may be left over for a bit

**Comment by RandomGuy91** [comment]
ok :0
