### ISSUE TITLE
[Bug]: Brutal Bosses causing NPE crash on latest DawnCraft 1.7

### ISSUE THREAD

**Issue by Dark-Matter-001** [someaddons/dungeonbosses#53]
### Describe the bug you're experiencing

DawnCraft 1.7 crashing on joining server due to BrutalBosses NullPointerException caused by Null boss in Bossbar code.
https://mclo.gs/2kFi55e

### Reproducability

Join a server when a [CaveSpider](id:brutalbosses:cavespiderboss) is in view range.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs and Datapacks

https://mclo.gs/2kFi55e

**Comment by someaddons** [comment]
could you send me the server's logs and datapack for brutal bosses? Its very likely related to those
