### ISSUE TITLE
[Bug]: Bosses not getting disabled via datapack 

### ISSUE THREAD

**Issue by Wolfstar1010** [someaddons/dungeonbosses#54]
### Describe the bug you're experiencing

Maybe I'm not doing this right, I tried to disable bosses via datapack as well as add custom bosses. The custom bosses work great! The ones I attempted to disable still spawn in the world. 

### Reproducability

I set up the datapack, transferred in all the files for existing bosses and cleared out their spawn chest locations (those are blank now). 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/Wolfstar1010/f4762048a9d03584eb838eaaf1b84387

**Comment by someaddons** [comment]
Please upload your datapack as zip, so I can see if paths etc are set correctly. Are you using some mod to globally load datapacks? or do you use vanilla's world folder

**Comment by Wolfstar1010** [comment]
[Ender Eye Loot Tweaks.zip](https://github.com/someaddons/dungeonbosses/files/11361398/Ender.Eye.Loot.Tweaks.zip)

We are using Paxi. This datapack has a lot of stuff in it but you should find brutalbosses in the data folder. I'm wondering if maybe the formatting I tried to remove them wasn't right? Should I try removing the entire "spawnatchest" section?

I added two bosses myself so far - the freakager and spiritcaller. Those are spawning at the right chests so I know that the datapack itself is working. Just for some reason the other bosses are still spawning at their various chests.

**Comment by someaddons** [comment]
ah that explains it, do not use paxi use global datapacks instead, paxi uses a wrong loading order causing mod resource to be loaded after datapacks and thus overwriting the datapack things

**Comment by Wolfstar1010** [comment]
Oh gosh that explains a few things actually. I'll give it a try later and let you know. Thanks!

**Comment by Wolfstar1010** [comment]
Looks like global datapacks is fabric only? Would open loader work better?

**Comment by someaddons** [comment]
![image](https://user-images.githubusercontent.com/38401808/236634902-cd05eef8-29ae-48b6-a668-c3530a7f8bd0.png)
there is versions for all mod loaders
