### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TylorTurner** [someaddons/dungeonbosses#55]
### Describe the bug you're experiencing

Repurposed Structures is crashing with Brutal Bosses 
"the wandering trader tries to generate its trades which hits Repurposed Structure's wandering trader map that locates rare Repurposed Structure's structures which causes the game to deadlock as the map search through vanilla' system is not worldgen safe and locks the chunk" From Repurposed Structures - TelepathicGrunt

### Reproducability

1.18.2 Forge
Repurposed Structures + Brutal Bosses
Pregen and Wait
This is my first Github post so if I did anything incorrectly. Well yeah.

[crash-2023-05-11_08.25.02-server.txt](https://github.com/someaddons/dungeonbosses/files/11452953/crash-2023-05-11_08.25.02-server.txt)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/TylorTurner/de5e2394f491a210fb098a377957c638

**Comment by someaddons** [comment]
try the newest version, should be fixed
