### ISSUE TITLE
[Bug]: NullPointerException "boss" has no size

### ISSUE THREAD

**Issue by Yourname942** [someaddons/dungeonbosses#56]
### Describe the bug you're experiencing

I am not sure if it is related to this: https://github.com/Infamous-Misadventures/Dungeons-Mobs/issues/179 (potentially the formatting)

[Render thread/ERROR]: Underlying Exception: 
java.lang.NullPointerException: Boss Item brutalbosses:snowgolemboss has no size!

![image](https://github.com/someaddons/dungeonbosses/assets/58750222/5c394912-22a3-47c8-b8d7-6876911478b5)

### Reproducability

1. Open Curseforge app
2. Create a new profile
3. MC 1.19.2
4. Forge 43.2.11
5. Install JEI
6. Install Brutal Bosses 6.2
7. Install Apotheosis 6.1.5
8. launch the game
9. create a new world (creative/hard)
10. enter the world
11. close the game
_observe the errors in the log file_

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs and Datapacks

https://paste.ee/p/cNcIU

**Comment by someaddons** [comment]
This is normal, apotheosis tries to load brutal bosses boss files which don't fit their json format
