### ISSUE TITLE
Minecraft Crash Ticking entity

### ISSUE THREAD

**Issue by OBS3SS1ON** [someaddons/dungeonbosses#57]
### Describe the bug you're experiencing

[crash-2023-05-19_23.56.52-server.txt](https://github.com/someaddons/dungeonbosses/files/11521462/crash-2023-05-19_23.56.52-server.txt)

### Reproducability

I'm fighting a zombie, I take half of its life and then the game closes

1.19.4-forge-45.0.57

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/OBS3SS1ON/f0caab40fddeece78aebeb38cfefcd3c

**Comment by someaddons** [comment]
fixed in 6.3
