### ISSUE TITLE
[Bug]: Having trouble controlling iframes with NoDami and Brutal Bosses

### ISSUE THREAD

**Issue by NighthowlerStudios** [someaddons/dungeonbosses#58]
### Describe the bug you're experiencing

From a look at the code it seems your melee damage system has a class that contains cooldown data, which is 30 by default.  With NoDami installed, this allows brutal bosses to spam damage 20 times per second, since somehow the behaviour is broken and it behaves as if cooldown is 0.  It looks like a bug in terms of calculating cooldown has been found

in any case, I would like assistance in my datapack to force all melee attacks to have some sort of delay in this way.  How would I go about doing that?  Unless it really is just a broken behaviour

### Reproducability

Install NoDami alongside Brutal Bosses
Spawn a melee attacking boss, such as a zombie
Stand next to the zombie as close and long as possible, and get spam damaged, instead of the intended 30 tick cooldown default

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/Kaleidio/6fcd2fd2e6561f152dd02c7d0ef8eaa5

**Comment by someaddons** [comment]
I'm no longer updating 1.16.5, and it sounds like nodami breaks things

**Comment by NighthowlerStudios** [comment]
I believe you misunderstood the purpose of my issue.  I would like to know how to forcefully summon a brutal boss using commands please.  That way I can test things and do some fixes as necessary.  no patching to your mod is required though I have given you the cause for my search in the first place

**Comment by NighthowlerStudios** [comment]
never mind, I've found the command

**Comment by NighthowlerStudios** [comment]
For future reference to anyone who may find this issue:

nodami removes iframes on all vanilla mobs by default.  Due to this it also causes some mobs that vanilla never gave a melee cooldown to not have one when giving a melee attack.  

Add those mobs to the cooldown exception blacklist in the nodami config to fix their melee.  this includes and is not limited to evokers, guardians, the wither, the ender dragon, etcetera.  adding them in this fashion fixes all problems in this issue.
