### ISSUE TITLE
[Bug]: java.lang.IllegalArgumentException: Modifier is already applied on this attribute!

### ISSUE THREAD

**Issue by SiverDX** [someaddons/dungeonbosses#59]
### Describe the bug you're experiencing

Was afk and the game crashed
Did not happen when I spawned multiple `huskboss` entities afterwards

Maybe could do a check if an attribute of that type was already set?
https://github.com/someaddons/dungeonbosses/blob/7e812e92407e5211da3c2546a824a41d65c81554/src/main/java/com/brutalbosses/entity/ai/ChargeGoal.java#L77

https://www.curseforge.com/minecraft/mc-mods/enemy-expansion modifies the entity
And there are some NBT-tags from https://www.curseforge.com/minecraft/mc-mods/obscure-api

But then again, it did not crash when I spawned them in

### Reproducability

Could not reproduce

Seems to be rare, first time it happened?

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/SiverDX/2b5a310681bc49d246dede1e10377e39

**Comment by someaddons** [comment]
fixed in 6.3
