### ISSUE TITLE
[Bug]: Spitcobweb seems broken

### ISSUE THREAD

**Issue by JetpackRescue** [someaddons/dungeonbosses#6]
### Describe the bug you're experiencing

brutalbosses:spitcobweb seems to be broken, when summoning the cavespiderboss or applying it to a different mob as a boss it just produces white particles around the spider, out of the several tests i've tried, i've only seen 1 cobweb and it spawned behind the mob, I was 10 blocks in front of the mob.

### Reproducability

summon cavespiderboss

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

It's not a crash

**Comment by someaddons** [comment]
fixed
