### ISSUE TITLE
[1.19.4][Crash]: Modifier is already applied on this attribute!

### ISSUE THREAD

**Issue by MrKashew** [someaddons/dungeonbosses#60]
### Describe the bug you're experiencing

I ate a golden apple while being attacked in nether, likely not having to do with the crash as per log:
https://gist.github.com/MrKashew/d210af32a86b4956cd0d89ef8eb5e24f

### Reproducability

I ate a golden apple while being attacked in nether, likely not having to do with the crash as per log:
https://gist.github.com/MrKashew/d210af32a86b4956cd0d89ef8eb5e24f

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/MrKashew/d210af32a86b4956cd0d89ef8eb5e24f

**Comment by someaddons** [comment]
you need to update to version 6.3, its been fixed already
