### ISSUE TITLE
[Bug]: Fabric version won't load on fabric

### ISSUE THREAD

**Issue by slammaja** [someaddons/dungeonbosses#62]
### Describe the bug you're experiencing

I installed mod on Minecraft 1.19.2 - Fabric 0.14.21 and it did not load. It is not listed i mod menu, nor can I use commands.

### Reproducability

Install on mentioned version. Version of mod 6,3

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs and Datapacks

https://gist.github.com/slammaja/2c263b84e3c2f21fad5bd3f6ff80e558

**Comment by someaddons** [comment]
fixed in 6.4, seems I accidently uploaded a broken/empty file
