### ISSUE TITLE
[Bug]: 6.4 crashes on fabric (probable incompatibility)

### ISSUE THREAD

**Issue by jozzo402** [someaddons/dungeonbosses#63]
### Describe the bug you're experiencing

When running the game after installing 6.4, the game immediately crashes (error log in gist). 
- The game launches fine if I remove this mod or if I downgrade back to 6.3.
- The game launches fine if I disable every other mod on my list

### Reproducability

Install 6.4 & run the game with my modlist (see bottom of gist). 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs and Datapacks

https://gist.github.com/jozzo402/846ccb75d6d4267f27ef615f39e12182

**Comment by someaddons** [comment]
report to pekhui, they have a ton of mixins

**Comment by someaddons** [comment]
fixed
