### ISSUE TITLE
[Bug]: Bosses spawning inside of blocks and suffocating

### ISSUE THREAD

**Issue by mxruben** [someaddons/dungeonbosses#64]
### Describe the bug you're experiencing

The bosses that spawn in the vanilla dungeon structures spawn inside of the walls, causing them to suffocate. I managed to get a screenshot of this happening:
![2023-07-28_16 12 09](https://github.com/someaddons/dungeonbosses/assets/89617289/c4856319-95d7-4ab2-b3e7-c05b3f9c3ce7)

### Reproducability

Create a world, teleport to the coordinates of a dungeon.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/mxruben/ef94469e7b404231da0e10d47a0bf99f

**Comment by someaddons** [comment]
fixed
