### ISSUE TITLE
[Bug]: Boss spawns so many minions when ai goal with Health Interval

### ISSUE THREAD

**Issue by KaxelDreamhack123** [someaddons/dungeonbosses#65]
### Describe the bug you're experiencing

I decided to make a custom boss, and came across such a joke. I looked at the sources of the cave spider and tested it, everything is ok, but deciding to add the same mechanics to my boss, then when it reaches 50-0 percent of HP, it will just spawn an armada, and then it will spawn normally. I don't know what it could be, I thought
that the interval seems to work constantly, trying to spawn the mob, but when he sees that the hp interval has not reached the desired mark, he does not spawn, but waits for this mark to appear in order to simply explode, however, I set the interval, for example, 10000, and yes, he exploded reaching this mark.
Maybe this is such a feature? It's just that I want to spawn the ultimate minions, like a mini-boss to the main boss, but when they appear somewhere around 7-8, firstly my fps tells me hello, take a nap, secondly I die because there are too many of them.

### Reproducability

Copy the code of the cave spider, adding only the health interval with a mark for example 50-0 or 25-0, I don’t know, but I think it will work ok on 100-0, but if not, it doesn’t matter, because there is no point in this function

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs and Datapacks

nothing

**Comment by someaddons** [comment]
sorry, but I'm no longer updating 1.18.2

**Comment by KaxelDreamhack123** [comment]
> sorry, but I'm no longer updating 1.18.2

Looks very bad
