### ISSUE TITLE
[Bug]: Crash on server

### ISSUE THREAD

**Issue by slammaja** [someaddons/dungeonbosses#66]
### Describe the bug you're experiencing

The server crashes after logging in.

### Reproducability

Install mod on server, log in.
[crash-2023-08-14_11.51.11-server.txt](https://github.com/someaddons/dungeonbosses/files/12333608/crash-2023-08-14_11.51.11-server.txt)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs and Datapacks

https://gist.github.com/slammaja/8d8e4cb6c7fdc9beef8578915e84caf8

**Comment by someaddons** [comment]
fixed in 6.6
