### ISSUE TITLE
[Bug]: [1.16.5]Projectiles cannot hit players

### ISSUE THREAD

**Issue by GoldenTotem** [someaddons/dungeonbosses#68]
### Describe the bug you're experiencing

Minecraft 1.16.5  Forge 36.2.35  Brutalbosses 4.7

The projectiles I shot cannot hit myself. For example, shoot an arrow or throw a splash potion upwards, it will go through my body.
Projectiles shot by other entities can still hit players. 
Projectiles shot by other players has not tested.

### Reproducability

Install brutalbosses 4.7 and shoot an arrow yourself

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16

### Modloader version

Forge

### Logs and Datapacks

_

**Comment by someaddons** [comment]
Sorry but I'm no longer updating 1.16.5

**Comment by GoldenTotem** [comment]
> Sorry but I'm no longer updating 1.16.5

Sorry, I can understand that it is not easy to maintain a non-latest version. But 1.16.5 has not dead and there is also many mods at this version and I need it for the modpack.
If you really don't want to give an update to 1.16.5, could you say something about the cause of the bug? Thanks very much.
