### ISSUE TITLE
[Bug][1.16.5]: Percent formula for SummonMobs OwnerDamagePct is incorrect

### ISSUE THREAD

**Issue by NighthowlerStudios** [someaddons/dungeonbosses#69]
### Describe the bug you're experiencing

Regardless of value set, the health of the mob goes down to a very low value the moment the first summon is killed, instead of working based on the brutalboss version of the mob's base health.  This can result in a zombie boss with 400 health returning to 40 health before percent is taken at all.

### Reproducability

Create a boss with any entity.
Give it an AI goal with brutalbosses:summonmobs and give that a ownerdamagepct of any value.
Kill any summoned minion from the boss and watch its health get absolutely destroyed.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/Kaleidio/5bb4b8b19415b4ecc879c290ca8e3f72

**Comment by someaddons** [comment]
Sorry but I'm no longer updating 1.16.5
