### ISSUE TITLE
[Bug]: Datapacks are loading after the ones provided by Paxi, causing custom datapack to be overriden

### ISSUE THREAD

**Issue by Colin-J-Wood** [someaddons/dungeonbosses#7]
### Describe the bug you're experiencing

I develop a modpack with very specific configuration which helps balance the bosses.  However, these configurations are completely forgotten by the mod's datapack loading order.

In order to fix datapack loading, you need to make sure your mod's datapack loads in *before* user provided (or paxi provided) ones and not after.

### Reproducability

Kaleidio's Battle Pack 4.2.10, update to latest brutal bosses.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs
https://pastebin.com/vvvbxCA9

**Comment by someaddons** [comment]
Loading order is done by forge and mods data is always loaded before any datapack, are you sure you've got the datapack in the right folder? And what is a paxi can I eat it?

**Comment by NighthowlerStudios** [comment]
Paxi is a datapack loading mod that lets you load datapacks like defaultconfig loads serverconfig.  modpack developers like myself can develop their own datapacks that every world created will have automatically installed.

paxi is loading them before yours does, and I don't exactly know why.

**Comment by NighthowlerStudios** [comment]
I think it has something to do with the fact you are shipping a zipped version of your data folder with the base version already present, causing minecraft to load the compressed version afterward.  please make sure you don't ship two data folders in that fashion.

**Comment by NighthowlerStudios** [comment]
![image](https://user-images.githubusercontent.com/82226641/155910119-db50dd37-b1d8-4f30-8e14-23ecd0e9f572.png)

**Comment by someaddons** [comment]
ah so paxi is another clone of a global datapacks mod

**Comment by someaddons** [comment]
the data zip wasnt intended to be included, but I dont think it matters as I can successfully load a datapack modification. You still did not mention the paths/folders your datapack is using btw, so I cannot verify that your datapack is actually in the correct place.

**Comment by NighthowlerStudios** [comment]
it is correct as my datapack is loading other mods' namespaces in the correct way.  when I used the datapack list command, it showed brutal bosses had loaded its own at least 20 packs after paxi-inserted ones.  all of those namespaces are provided in a single pack I created but twenty or so mods load after it anyway.  your mod is the only one that causes issue by loading afterward

I'm in touch with Yung to see if he can fix the loading order but I have a feeling he will say it is up to devs such as yourself to make sure things work correctly

**Comment by NighthowlerStudios** [comment]
I still recommend removing the .zip version for the purpose of debloating and assurance.  I will test again now with it manually removed from the jar.

**Comment by NighthowlerStudios** [comment]
![image](https://user-images.githubusercontent.com/82226641/155970920-f4b7fb02-a25a-445b-96ab-b7d0b6c5c656.png)
didn't fix anything.  but proof of datapack ordering.

**Comment by NighthowlerStudios** [comment]
note I only started experiencing this issue post 2.6.  does it have something to do with your fixes for world loading?

**Comment by NighthowlerStudios** [comment]
thanks for the debloat fix.  keeping this tracker open until a paxi know-about gets in touch with me on the loading order issues.

**Comment by someaddons** [comment]
could also try another mod like global datapacks instead

**Comment by NighthowlerStudios** [comment]
yeah gonna do that next.  was busy for a moment

**Comment by NighthowlerStudios** [comment]
looks like global data and resource packs mod does this better.  Closing on this side and leaving the issue up to Paxi.
