### ISSUE TITLE
[Bug][1.16.5]: Boss projectiles in summoning circle not destroyed if the boss dies

### ISSUE THREAD

**Issue by NighthowlerStudios** [someaddons/dungeonbosses#70]
### Describe the bug you're experiencing

Self explanatory.  However, the projectiles are automatically destroyed normally ONLY if the boss is killed via a command.

### Reproducability

Summon a boss that fires projectiles
Kill the boss before it can throw its projectiles
The projectiles will hang in the air, ignore collisions, though they disappear on reload.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16

### Modloader version

Forge

### Logs and Datapacks

N/A

**Comment by someaddons** [comment]
Sorry but I'm no longer updating 1.16.5
