### ISSUE TITLE
[Bug]: Corail Tombstone grave deletion

### ISSUE THREAD

**Issue by GothCartel** [someaddons/dungeonbosses#71]
### Describe the bug you're experiencing

Ewart the Cold's lightning attack can in certain circumstances create a double kill which deletes players inventory before a grave can be created thus losing all players items.

### Reproducability

When fighting Ewart the cold if struck by an arrow and then a lightning strike it will delete the players grave

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs and Datapacks

do not currently have logfile with death but upon previous instances it has never shown the kill

**Comment by someaddons** [comment]
The lightning bolt is vanilla minecraft and only replaces air blocks, see the vanilla code: 
![image](https://github.com/someaddons/dungeonbosses/assets/38401808/cf8b0228-b3fd-4ebd-9e34-216e6e342baa)

If this manages to kill a gravestone something is off on the gravestone mod

**Comment by Corail31** [comment]
@someaddons Graves can't be destroyed by lightning (the grave reappears automatically). It's about how are done the damages (not like vanilla for sure), leading to a drop event empty, so no grave.

**Comment by Baenjamin** [comment]
This as well happens with the corpse mod. And it also makes it so journeymap doesn't add a death marker. And i'd assume it happen to any "graveyard" mod, and any map mod that usually adds a death marker on death. I will have to disable this mod until this issue has been fixed i guess.
