### ISSUE TITLE
[Bug]: Command to summon bosses is refusing to work [1.20.1]

### ISSUE THREAD

**Issue by cr4pshooter** [someaddons/dungeonbosses#73]
### Describe the bug you're experiencing

I type in the command to summon a boss, and nothing happens. Whether I put a specific name or try to summon a random boss, it just does nothing. I only downloaded it today, so it's the most recent version

### Reproducability

I type in the command to summon a boss, and nothing happens. Whether I put a specific name or try to summon a random boss, it just does nothing. I only downloaded it today, so it's the most recent version

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/cr4pshooter/3ce2c875f9785b5ca730dca0b0b2322a

**Comment by someaddons** [comment]
make sure to use the proper filename, e.g. seen here: https://github.com/someaddons/dungeonbosses/blob/1.20.1/src/main/resources/data/brutalbosses/bosses/cavespiderboss.json
its "cavespiderboss"
you can also put in "random" or "all"

I did find a bug causing invalid spawn positions though, update the cupboard dependency to 2.6
