### ISSUE TITLE
[Feedback] Default config

### ISSUE THREAD

**Issue by Nyoha12** [someaddons/dungeonbosses#74]
### Describe the bug you're experiencing

Hello there, just to give you my feedback about the default config, I find the mobs waaaaaay too strongs, maybe because playing on a modpack with autoleveling, ratios get crazy 

### Reproducability

playin with cisco ultimate medieval modpack

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs and Datapacks

https://www.curseforge.com/minecraft/modpacks/ciscos-adventure-rpg-ultimate

**Comment by someaddons** [comment]
Hi, it might be that autoleveling scales them up too much, however every boss is created via datapacks and can be modified that way, so the pack should probably scale them down via datapacks then
