### ISSUE TITLE
[Feature]: Coordinate support for the spawn boss command 

### ISSUE THREAD

**Issue by DaddySpin** [someaddons/dungeonbosses#75]
### Describe the bug you're experiencing

I want to be able to use the spawn boss command with a command/mcfunction, but it doesn't support coordinates.

### Reproducability

running the command in a command block does nothing.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs and Datapacks

n/a

**Comment by someaddons** [comment]
the mods commands are meant to test the bosses ingame, if you want to summon it specifically I'd suggest to use the vanilla summon command instead with nbt of a boss

can also use ```/execute positioned ~ ~ ~ run  ```

**Comment by someaddons** [comment]
e.g. with ```/data get entity @e[distance=..10, limit=1, type=!minecraft:player]``` you can get the closest entities nbt

**Comment by DaddySpin** [comment]
So if you grab the nbt and summon it with that will it still have the custom attacks?

**Comment by someaddons** [comment]
ye, thats how the bosses are saved in world aswell, custom data on a normal entity

**Comment by DaddySpin** [comment]
Seems to work. also heads up the execute command does not work in command blocks for the spawn boss command.

**Comment by someaddons** [comment]
hm I might've used the player entity in the command ye, I'll check if I can avoid it

**Comment by DaddySpin** [comment]
That would be awesome

**Comment by someaddons** [comment]
lowered the permission level required to allow command blocks in 7.0
