### ISSUE TITLE
[Bug]: LivingDeathMixin can cause issues with other mods

### ISSUE THREAD

**Issue by Ayutac** [someaddons/dungeonbosses#76]
### Describe the bug you're experiencing

The line
`final BossCapability cap = ((BossCapEntity)(Object)this).getBossCap();`
in LivingDeathMixin can cause Class cast exceptions, which crashes the game. Please add a proper check. This issue is still existing on newer versions as well, as the code hasn't changed.

### Reproducability

With the JCraft mod:
`/stand set YourName MAGICIAN_RED`
Then use Special 3 attack (default: M) of Magician Red on a sheep or something.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs and Datapacks

https://gist.github.com/Ayutac/bcf4ffe05802a9fcaaeaec0edb9fe692

**Comment by someaddons** [comment]
fixed in 6.9
