### ISSUE TITLE
[Bug]: Customizing existing bosses files or making new using datapack disables summonmobs ai behaviour

### ISSUE THREAD

**Issue by VoidFlower** [someaddons/dungeonbosses#77]
### Describe the bug you're experiencing

Tried to make new boss using datapack json files. Everything works fine except brutalbosses:summonmobs ai-goal. The game ignores this behaviour and never activates it. 
Adding datapack with default mod bosses to the world also disables summoning ai-goal on bosses "evokersummoner" and "cavespiderboss". Without datapack summoning behaviour works as intended.

### Reproducability

1) Install minecraft instance 1.20.1
2) Install brutalbosses mod (1.20.1-6.8) and cupboard (1.20.1-2.6)
3) Launch minecraft instance and create "new world"
4) Create datapack with brutalbosses/bosses/evokersummoner.json with default values and add it to the "new world"
5) Enter the world and summon boss using command /brutalbosses summonboss evokersummoner
6) Evokersummner doesn't summon mobs
6.1) Disable datapack and summon new evoker, it now summons mobs

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs and Datapacks

https://gist.github.com/VoidFlower/453042713d73fd8f444cab27cd880c1f

**Comment by someaddons** [comment]
oh you're using the old 1.16 format, in 1.20.1 it is different:
```
      "entities": [
        {
          "entityid": "minecraft:zombie",
          "entitynbt": "{Brain: {memories: {}}, HurtByTimestamp: 251, IsBaby: 1b, Attributes: [{Base: 0.0d, Name: \"minecraft:zombie.spawn_reinforcements\"}, {Base: 0.08d, Name: \"forge:entity_gravity\"}, {Base: 0.23000000417232513d, Name: \"minecraft:generic.movement_speed\"}], Invulnerable: 0b, FallFlying: 0b, PortalCooldown: 0, AbsorptionAmount: 0.0f, InWaterTime: -1, FallDistance: 0.0f, CanUpdate: 1b, DeathTime: 0s, ForgeCaps: {\"brutalbosses:bosscap\": {}}, HandDropChances: [0.085f, 0.085f], PersistenceRequired: 0b, UUID: [I; -1356225159, 445793596, -1560838011, 528914832], Motion: [0.0d, -0.0784000015258789d, 0.0d], Health: 18.119999f, LeftHanded: 0b, Air: 300s, OnGround: 1b, Rotation: [88.88051f, 0.0f], HandItems: [{}, {}], ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f], Pos: [-59.22638885988113d, 55.0d, 100.53636996754722d], CanBreakDoors: 0b, Fire: -1s, ArmorItems: [{}, {}, {}, {}], CanPickUpLoot: 0b, HurtTime: 0s, DrownedConversionTime: -1}"
        },
        {
          "entityid": "minecraft:skeleton"
        },
        {
          "entityid": "minecraft:husk"
        },
        {
          "entityid": "minecraft:wither_skeleton"
        },
        {
          "entityid": "minecraft:stray"
        }
      ]
      ```
