### ISSUE TITLE
[Bug]: Zombie boss to drowned sound effect spam

### ISSUE THREAD

**Issue by polykatt** [someaddons/dungeonbosses#79]
### Describe the bug you're experiencing

The zombie boss "Corvin the Rotten" doesn't turn into a drowned when underwater for long enough. That's expected but it continuously plays the sound effect for the transformation which is really loud and loops forever until it is killed.

Minecraft version 1.21.1

### Reproducability

Place "Corvin the Rotten" under water for long enough that a zombie would take to turn into a drowned

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.4

### Modloader version

Fabric

### Logs and Datapacks

https://gist.github.com/polykatt/8a2d21c4fe777181545e7ab18c06b9f9

**Comment by someaddons** [comment]
fixed
