### ISSUE TITLE
[Bug]: 1.18.1 weird error on servers tart

### ISSUE THREAD

**Issue by itsdinkd** [someaddons/dungeonbosses#8]
### Describe the bug you're experiencing

When a dedicated server is fully started, and world spawned in, you get this funky error. 

### Reproducability

start server
watch console/logs

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/itsdinkd/62d0ca53979caa7a29414cbeb166cbe2

**Comment by someaddons** [comment]
thats actually an issue of the armor plus mod, please open a bug report on their side, they're creating entities with returning a null entity type.

**Comment by itsdinkd** [comment]
will do, thanks! 

by the way, I didn't even notice you made this mod, awesome. irrelevant but I'm a patreon supporter of yours. When will you be releasing Performant out to the public? would love to add into my modpack as soon as its out (currently use it in the official server for the pack)
